import type { Metadata } from "next";
import { Inter, Manjari, Fraunces } from "next/font/google";
import { Analytics } from "@vercel/analytics/next";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const manjari = Manjari({
  subsets: ["latin"],
  variable: "--font-manjari",
  weight: "400",
});

const fraunces = Fraunces({
  subsets: ["latin"],
  variable: "--font-fraunces",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Bartlomiej Perucki | Web Developer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${manjari.variable} ${fraunces.variable} antialiased`}
      >
        <Analytics />
        <div className="max-w-[1240px] mx-auto">
          <div className="px-4 md:px-8 lg:px-16">{children}</div>
        </div>
      </body>
    </html>
  );
}
